"use server";

import { revalidatePath } from "next/cache";
import { requireAdmin, readableError } from "@/lib/actions/guard";
import { bulkSpecError, planSessions, type BulkSpec } from "@/lib/rules/schedule";
import type { ActionResult } from "@/lib/actions/bookings";

function refresh(sessionId?: string) {
  revalidatePath("/admin");
  revalidatePath("/admin/schedule");
  if (sessionId) revalidatePath(`/admin/schedule/${sessionId}`);
  revalidatePath("/app");
  revalidatePath("/app/book");
}

function readSpec(formData: FormData): BulkSpec {
  return {
    weekdays: formData.getAll("weekdays").map((d) => Number(d)).filter((d) => Number.isFinite(d)),
    time: String(formData.get("time") ?? ""),
    durationMinutes: Number(formData.get("duration") ?? 60),
    from: String(formData.get("from") ?? ""),
    to: String(formData.get("to") ?? ""),
  };
}

/** One session, from the "New session" form. */
export async function createSession(_prev: ActionResult | null, formData: FormData): Promise<ActionResult> {
  const guard = await requireAdmin();
  if (!guard.ok) return guard;

  const classTypeId = String(formData.get("class_type_id") ?? "");
  const venueId = String(formData.get("venue_id") ?? "");
  const coachId = String(formData.get("coach_id") ?? "");
  const date = String(formData.get("date") ?? "");
  const time = String(formData.get("time") ?? "");
  const duration = Number(formData.get("duration") ?? 60);
  const capacity = Number(formData.get("capacity") ?? 20);
  const notes = String(formData.get("notes") ?? "").trim();

  if (!classTypeId || !venueId) return { ok: false, error: "Pick a class type and a venue." };
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) return { ok: false, error: "Pick a date." };
  if (!/^([01]\d|2[0-3]):[0-5]\d$/.test(time)) return { ok: false, error: "Enter a time as HH:mm." };
  if (!Number.isFinite(capacity) || capacity < 1) return { ok: false, error: "Capacity must be at least 1." };
  if (!Number.isFinite(duration) || duration < 1) return { ok: false, error: "Duration must be at least a minute." };

  const startsAt = new Date(`${date}T${time}:00+08:00`);
  const endsAt = new Date(startsAt.getTime() + duration * 60_000);

  const { error } = await guard.supabase.from("sessions").insert({
    class_type_id: classTypeId,
    venue_id: venueId,
    coach_id: coachId || null,
    starts_at: startsAt.toISOString(),
    ends_at: endsAt.toISOString(),
    capacity,
    notes: notes || null,
  });
  if (error) return { ok: false, error: readableError(error.message, "Could not create that session.") };

  refresh();
  return { ok: true, message: "Session created." };
}

/**
 * A recurrence, from the "Bulk create" form. The plan is generated by
 * lib/rules/schedule.ts so the admin can be shown the count before confirming.
 */
export async function bulkCreateSessions(_prev: ActionResult | null, formData: FormData): Promise<ActionResult> {
  const guard = await requireAdmin();
  if (!guard.ok) return guard;

  const classTypeId = String(formData.get("class_type_id") ?? "");
  const venueId = String(formData.get("venue_id") ?? "");
  const coachId = String(formData.get("coach_id") ?? "");
  const capacity = Number(formData.get("capacity") ?? 20);
  if (!classTypeId || !venueId) return { ok: false, error: "Pick a class type and a venue." };
  if (!Number.isFinite(capacity) || capacity < 1) return { ok: false, error: "Capacity must be at least 1." };

  const spec = readSpec(formData);
  const problem = bulkSpecError(spec);
  if (problem) return { ok: false, error: problem };

  const planned = planSessions(spec);
  const { error } = await guard.supabase.from("sessions").insert(
    planned.map((p) => ({
      class_type_id: classTypeId,
      venue_id: venueId,
      coach_id: coachId || null,
      starts_at: p.startsAt.toISOString(),
      ends_at: p.endsAt.toISOString(),
      capacity,
    })),
  );
  if (error) return { ok: false, error: readableError(error.message, "Could not create those sessions.") };

  refresh();
  return { ok: true, message: `Created ${planned.length} sessions.` };
}

/** Cancels a session and refunds every booked member (admin_cancel_session). */
export async function cancelSession(sessionId: string): Promise<ActionResult> {
  const guard = await requireAdmin();
  if (!guard.ok) return guard;

  const { data, error } = await guard.supabase.rpc("admin_cancel_session", { p_session_id: sessionId });
  if (error) return { ok: false, error: readableError(error.message, "Could not cancel that session.") };

  const row = (data as { cancelled: number; refunded: number }[] | null)?.[0];
  refresh(sessionId);
  return {
    ok: true,
    message: `Session cancelled. ${row?.cancelled ?? 0} bookings released, ${row?.refunded ?? 0} credits returned.`,
  };
}

/** Coach, capacity and notes on an existing session. */
export async function updateSession(_prev: ActionResult | null, formData: FormData): Promise<ActionResult> {
  const guard = await requireAdmin();
  if (!guard.ok) return guard;

  const id = String(formData.get("session_id") ?? "");
  const coachId = String(formData.get("coach_id") ?? "");
  const capacity = Number(formData.get("capacity") ?? 0);
  const notes = String(formData.get("notes") ?? "").trim();
  if (!id) return { ok: false, error: "Missing session." };
  if (!Number.isFinite(capacity) || capacity < 1) return { ok: false, error: "Capacity must be at least 1." };

  const { error } = await guard.supabase
    .from("sessions")
    .update({ coach_id: coachId || null, capacity, notes: notes || null })
    .eq("id", id);
  if (error) return { ok: false, error: readableError(error.message, "Could not save that session.") };

  refresh(id);
  return { ok: true, message: "Session saved." };
}
